# ?? ?????????
spring.application.name=ScooterFlow

# ????? ??? ??????? - ???? ????? ????? ??????? data
spring.datasource.url=jdbc:h2:file:./data/scooter-flow-db;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ????? ???? ?????? ?? H2 ??????
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# ????? ???? ??????? - 'update' ???? ?? ??????? ??????? ??? ???? ????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ????? ????? Open-In-View
spring.jpa.open-in-view=false

# ????? ??? ?????? (???????)
spring.jackson.time-zone=GMT+2

spring.sql.init.mode=always